import { Router, type IRouter } from "express";

const router: IRouter = Router();

const menuData = {
  sections: [
    {
      category: "appetizers",
      items: [
        {
          id: "app-1",
          name: "Truffle Arancini",
          description: "Crispy saffron risotto balls filled with black truffle and aged fontina, served with roasted tomato coulis.",
          price: 24,
          category: "appetizers",
          image: null,
          tags: ["vegetarian"],
          calories: 420,
          allergens: "Gluten, Dairy, Eggs",
        },
        {
          id: "app-2",
          name: "Seared Scallops",
          description: "Pan-seared day-boat scallops with cauliflower purée, crispy capers, and lemon brown butter.",
          price: 32,
          category: "appetizers",
          image: null,
          tags: ["gluten-free"],
          calories: 310,
          allergens: "Shellfish, Dairy",
        },
        {
          id: "app-3",
          name: "Wagyu Beef Tartare",
          description: "Hand-cut A5 wagyu, shallots, cornichons, quail egg yolk, house-made sourdough crisps.",
          price: 38,
          category: "appetizers",
          image: null,
          tags: [],
          calories: 380,
          allergens: "Eggs, Gluten",
        },
        {
          id: "app-4",
          name: "Heirloom Beet Carpaccio",
          description: "Roasted golden and red beets, goat cheese mousse, candied walnuts, micro-arugula, aged balsamic.",
          price: 19,
          category: "appetizers",
          image: null,
          tags: ["vegetarian", "gluten-free"],
          calories: 280,
          allergens: "Dairy, Tree Nuts",
        },
        {
          id: "app-5",
          name: "Burrata & Stone Fruit",
          description: "House-made burrata, grilled peaches, heirloom cherry tomatoes, basil oil, Maldon sea salt.",
          price: 22,
          category: "appetizers",
          image: null,
          tags: ["vegetarian", "gluten-free"],
          calories: 350,
          allergens: "Dairy",
        },
      ],
    },
    {
      category: "mains",
      items: [
        {
          id: "main-1",
          name: "Dry-Aged Prime Ribeye",
          description: "28-day dry-aged 14oz ribeye, roasted bone marrow butter, pommes sarladaises, seasonal greens.",
          price: 89,
          category: "mains",
          image: null,
          tags: ["gluten-free"],
          calories: 980,
          allergens: "Dairy",
        },
        {
          id: "main-2",
          name: "Pan-Roasted Halibut",
          description: "Pacific halibut, saffron beurre blanc, grilled asparagus, confit fingerling potatoes, chervil oil.",
          price: 62,
          category: "mains",
          image: null,
          tags: ["gluten-free"],
          calories: 540,
          allergens: "Fish, Dairy",
        },
        {
          id: "main-3",
          name: "Braised Short Rib",
          description: "48-hour red wine braised beef short rib, celery root purée, glazed cipollini, natural jus.",
          price: 74,
          category: "mains",
          image: null,
          tags: ["gluten-free"],
          calories: 820,
          allergens: "Dairy",
        },
        {
          id: "main-4",
          name: "Wild Mushroom Risotto",
          description: "Carnaroli rice, porcini, chanterelle and black trumpets, aged parmigiano, white truffle oil.",
          price: 46,
          category: "mains",
          image: null,
          tags: ["vegetarian", "gluten-free"],
          calories: 620,
          allergens: "Dairy",
        },
        {
          id: "main-5",
          name: "Duck Confit",
          description: "Slow-rendered Muscovy duck leg, cherry gastrique, farro piccolo, wilted Swiss chard, duck jus.",
          price: 58,
          category: "mains",
          image: null,
          tags: [],
          calories: 760,
          allergens: "Gluten, Dairy",
        },
        {
          id: "main-6",
          name: "Roasted Cauliflower Steak",
          description: "Whole roasted cauliflower, romesco sauce, toasted pine nuts, preserved lemon gremolata, harissa.",
          price: 38,
          category: "mains",
          image: null,
          tags: ["vegan", "gluten-free"],
          calories: 380,
          allergens: "Tree Nuts",
        },
      ],
    },
    {
      category: "desserts",
      items: [
        {
          id: "des-1",
          name: "Dark Chocolate Fondant",
          description: "Valrhona 72% dark chocolate fondant, Tahitian vanilla bean ice cream, gold leaf, cocoa tuile.",
          price: 18,
          category: "desserts",
          image: null,
          tags: ["vegetarian"],
          calories: 580,
          allergens: "Gluten, Dairy, Eggs",
        },
        {
          id: "des-2",
          name: "Crème Brûlée",
          description: "Classic Madagascar vanilla crème brûlée, caramelized crust, seasonal macerated berries.",
          price: 16,
          category: "desserts",
          image: null,
          tags: ["vegetarian", "gluten-free"],
          calories: 440,
          allergens: "Dairy, Eggs",
        },
        {
          id: "des-3",
          name: "Tarte Tatin",
          description: "Upside-down caramelized apple tart, flaky house-made pastry, crème fraîche, calvados caramel.",
          price: 17,
          category: "desserts",
          image: null,
          tags: ["vegetarian"],
          calories: 510,
          allergens: "Gluten, Dairy, Eggs",
        },
        {
          id: "des-4",
          name: "Seasonal Cheese Selection",
          description: "Curated three-cheese board, fig compote, honeycomb, walnut bread, seasonal accompaniments.",
          price: 24,
          category: "desserts",
          image: null,
          tags: ["vegetarian"],
          calories: 520,
          allergens: "Dairy, Gluten, Tree Nuts",
        },
      ],
    },
    {
      category: "drinks",
      items: [
        {
          id: "drk-1",
          name: "WARGO Signature",
          description: "Aged cognac, house-made elderflower cordial, fresh lemon, Champagne float, edible gold.",
          price: 28,
          category: "drinks",
          image: null,
          tags: [],
          calories: 220,
          allergens: null,
        },
        {
          id: "drk-2",
          name: "Smoked Old Fashioned",
          description: "Buffalo Trace bourbon, cherry-wood smoked demerara, Angostura bitters, expressed orange peel.",
          price: 24,
          category: "drinks",
          image: null,
          tags: [],
          calories: 190,
          allergens: null,
        },
        {
          id: "drk-3",
          name: "Garden Spritz",
          description: "Hendrick's gin, St-Germain, cucumber water, fresh herbs, Fever-Tree elderflower tonic.",
          price: 21,
          category: "drinks",
          image: null,
          tags: [],
          calories: 170,
          allergens: null,
        },
        {
          id: "drk-4",
          name: "Non-Alcoholic Botanicals",
          description: "House-blended botanical infusion, yuzu, lemongrass, ginger, sparkling water. Complex and refreshing.",
          price: 14,
          category: "drinks",
          image: null,
          tags: ["vegan", "gluten-free"],
          calories: 80,
          allergens: null,
        },
        {
          id: "drk-5",
          name: "Reserve Wine — Sommelier's Selection",
          description: "Ask your server for today's curated pour from our 800-bottle cellar. Priced by the glass.",
          price: 22,
          category: "drinks",
          image: null,
          tags: [],
          calories: 140,
          allergens: null,
        },
      ],
    },
  ],
};

router.get("/menu", async (_req, res): Promise<void> => {
  res.json(menuData);
});

export default router;
